// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/app/components/Providers';
import { Toaster } from 'sonner';
import { Auth0Provider } from '@auth0/nextjs-auth0';
import { Header } from './components/layout/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <Auth0Provider>
        <body className={inter.className}>
          <Providers>
            <Header />
            {children}
            <Toaster richColors />
          </Providers>
        </body>
      </Auth0Provider>
    </html>
  );
}
